import "../../globals.css";
import type { Metadata } from "next";
import { Frank_Ruhl_Libre, Inter, Lato } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const frankRuhlLibre = Frank_Ruhl_Libre({ subsets: ["latin"] });
const lato = Lato({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {},
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${frankRuhlLibre.className} ${lato.className}}`}
      >
        {children}
      </body>
    </html>
  );
}
